In [3]:
import pandas as pd 
df = pd.read_csv(r"C:\Users\K. AJAY SRIRAM\Downloads\customer_shopping_behavior.csv")

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info

<bound method DataFrame.info of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [6]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [9]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [13]:
df['Age Group'] = df['Age'].apply(lambda x: 'young' if x <=20 else
 'young_adult' if x <=30 else
 'adult' if x <=50 else 
 'old')

In [14]:
df.head(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Age Group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,old
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,adult
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young_adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,adult

In [18]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [21]:
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount_(usd)', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'promo_code_used', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'age_group']

In [22]:
df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'}, inplace=True)

In [23]:
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'promo_code_used', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'age_group']

In [26]:
df['payment_mode'] = df['payment_method'].apply(lambda x:'Digital' if x in ['Venmo','Credit Card','Debit Card','PayPal','Bank Transfer']  else
'cash')

In [27]:
df.head(20)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,payment_mode
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,old,Digital
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young,cash
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,adult,Digital
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young_adult,Digital
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,adult,Digital
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly,adult,Digital
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly,old,cash
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly,young_adult,Digital
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually,young_adult,Digital
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly,old,cash
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,4.1,Yes,Store Pickup,Yes,Yes,26,Bank Transfer,Bi-Weekly,old,Digital
11,12,30,Male,Shorts,Clothing,68,Hawaii,S,Olive,Winter,4.9,Yes,Store Pickup,Yes,Yes,10,Bank Transfer,Fortnightly,young_adult,Digital
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,4.5,Yes,Express,Yes,Yes,37,Venmo,Fortnightly,old,Digital
13,14,65,Male,Dress,Clothing,51,New Hampshire,M,Violet,Spring,4.7,Yes,Express,Yes,Yes,31,PayPal,Weekly,old,Digital
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,4.7,Yes,Free Shipping,Yes,Yes,34,Debit Card,Weekly,old,Digital
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,2.8,Yes,Store Pickup,Yes,Yes,8,PayPal,Monthly,old,Digital
16,17,25,Male,Sunglasses,Accessories,36,Alabama,S,Gray,Spring,4.1,Yes,Next Day Air,Yes,Yes,44,Debit Card,Bi-Weekly,young_adult,Digital
17,18,53,Male,Dress,Clothing,38,Mississippi,XL,Lavender,Winter,4.7,Yes,2-Day Shipping,Yes,Yes,36,Venmo,Quarterly,old,Digital
18,19,52,Male,Sweater,Clothing,48,Montana,S,Black,Summer,4.6,Yes,Free Shipping,Yes,Yes,17,Cash,Weekly,old,cash
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,3.3,Yes,Standard,Yes,Yes,46,Debit Card,Bi-Weekly,old,Digital

In [28]:
df['reviews'] = df['review_rating'].apply(lambda x: 'Excellent' if x > 4 else
'Good' if x > 3 else 'Average' if x > 2 else 'Poor')

In [31]:
df[['reviews','review_rating']]

        reviews  review_rating
0          Good            3.1
1          Good            3.1
2          Good            3.1
3          Good            3.5
4       Average            2.7
...         ...            ...
3895  Excellent            4.2
3896  Excellent            4.5
3897    Average            2.9
3898       Good            3.8
3899       Good            3.1

[3900 rows x 2 columns]

In [32]:
df.head(20)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,...,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,payment_mode,reviews
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,...,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,old,Digital,Good
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,...,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young,cash,Good
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,...,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,adult,Digital,Good
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,...,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young_adult,Digital,Good
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,...,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,adult,Digital,Average
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,...,Yes,Standard,Yes,Yes,14,Venmo,Weekly,adult,Digital,Average
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,...,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly,old,cash,Good
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,...,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly,young_adult,Digital,Good
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,...,Yes,Express,Yes,Yes,8,Venmo,Annually,young_adult,Digital,Average
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,...,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly,old,cash,Excellent
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,...,Yes,Store Pickup,Yes,Yes,26,Bank Transfer,Bi-Weekly,old,Digital,Excellent
11,12,30,Male,Shorts,Clothing,68,Hawaii,S,Olive,Winter,...,Yes,Store Pickup,Yes,Yes,10,Bank Transfer,Fortnightly,young_adult,Digital,Excellent
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,...,Yes,Express,Yes,Yes,37,Venmo,Fortnightly,old,Digital,Excellent
13,14,65,Male,Dress,Clothing,51,New Hampshire,M,Violet,Spring,...,Yes,Express,Yes,Yes,31,PayPal,Weekly,old,Digital,Excellent
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,...,Yes,Free Shipping,Yes,Yes,34,Debit Card,Weekly,old,Digital,Excellent
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,...,Yes,Store Pickup,Yes,Yes,8,PayPal,Monthly,old,Digital,Average
16,17,25,Male,Sunglasses,Accessories,36,Alabama,S,Gray,Spring,...,Yes,Next Day Air,Yes,Yes,44,Debit Card,Bi-Weekly,young_adult,Digital,Excellent
17,18,53,Male,Dress,Clothing,38,Mississippi,XL,Lavender,Winter,...,Yes,2-Day Shipping,Yes,Yes,36,Venmo,Quarterly,old,Digital,Excellent
18,19,52,Male,Sweater,Clothing,48,Montana,S,Black,Summer,...,Yes,Free Shipping,Yes,Yes,17,Cash,Weekly,old,cash,Excellent
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,...,Yes,Standard,Yes,Yes,46,Debit Card,Bi-Weekly,old,Digital,Good

In [37]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\k. ajay sriram\appdata\local\programs\python\python313\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\k. ajay sriram\appdata\local\programs\python\python313\lib\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in c:\users\k. ajay sriram\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\k. ajay sriram\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.13.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

# Step 1 — Connection
url = URL.create(
    drivername = "postgresql+psycopg2",
    username   = "postgres",
    password   = "qwerty@123",    # replace with your password
    host       = "localhost",
    port       = 5432,
    database   = "postgres"
)
engine = create_engine(url)

# Step 2 — Check your cleaned df before pushing
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print(df.head(3))

# Step 3 — Push cleaned df to PostgreSQL
df.to_sql(
    name      = 'customer_shopping',
    con       = engine,
    if_exists = 'replace',
    index     = False
)

print("✅ Data pushed successfully!")

Shape: (3900, 21)
Columns: ['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'promo_code_used', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'age_group', 'payment_mode', 'reviews']
   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73

        location size   color  season  ...  subscription_status  \
0       Kentucky    L    Gray  Winter  ...                  Yes
1          Maine    L  Maroon  Winter  ...                  Yes
2  Massachusetts    S  Maroon  Spring  ...                  Yes

   shipping_type discount_applied promo_code_used previous_purchases  \
0        Express              Yes             Yes                 14
1        Express              Yes             Yes                  2
2  Free Shipping              Yes             Yes                 23

   payment_method frequency_of_purchases age_group payment_mode reviews
0           Venmo            Fortnightly       old      Digital    Good
1            Cash            Fortnightly     young         cash    Good
2     Credit Card                 Weekly     adult      Digital    Good

[3 rows x 21 columns]
✅ Data pushed successfully!

In [43]:
# Run this in jupyter notebook
from sqlalchemy import inspect

inspector = inspect(engine)
tables = inspector.get_table_names()
print("Tables in PostgreSQL:", tables)

Tables in PostgreSQL: ['customer_shopping']